name: Latest portfolio
on:
  schedule:
      # Runs at the end of every day. You can customise according to your need. You can also trigger this action for other events. Check github actions page for that.
      - cron: '0 0 * * *'
  workflow_dispatch:

jobs:     
  job_1:
    name: update-index-with-project
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: kaustubhgupta/PortfolioFy@v1.0
          with:
            gh_token: ${{ secrets.TOKEN }} # Create a secret for access token and modify the name as you wish
  
        - uses: test-room-7/action-update-file@v1
          with:
            file-path: |
              index.html
            commit-msg: index file added
            github-token: ${{ secrets.TOKEN }}
Usage
This action generates a index.html file which is website ready. Simply enable the GitHub pages to deploy the index file and boom, you have your portfolio which self updates when you add your projects or hackathons projects!

Add Blogs updatation
There is an action called Blog Post Workflow which updates latest blogpost on schedule. You can easily integrate this in your workflow via this method: (I highly recommend to use this!)

name: Latest blog post workflow
on:
  push:  # Everytime index.html is pushed, this action runs and updates the blogs section!
    
jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: gautamkrishnar/blog-post-workflow@master
          with:
            feed_list: <Your feedlist>
            max_post_count: 7
            readme_path: index.html
            template: "$newline <h2 class='h2-blog'><a class='a-lightblue' href=$url>$title</a></h2>$newline <br>"  # Do not change the template as it will not render good results!
            gh_token: ${{ secrets.TOKEN }}
